### PR TITLE
Its Vs It's

### PR DESCRIPTION
**Pull request by edent**
http://grammarist.com/spelling/its-its/

Sorry, it was bugging me :-)

### CODE REVIEW

**Comment by TPS** [comment]
@All @palant Is there any hope to receive any further updates/releases/betas/*anything* for this project?  For many, __many__ Android users, Adblock browser (nor *any* Mozilla-based browser) is NOT functional, & we are stuck with an increasingly-decrepit version of AB+A that regularly crashes with NO viable alternatives.…

**Comment by palant** [comment]
@rjeschke Could you look at this pull request?

@TPS Any particular reason why you chose to hijack this pull request? Sure, we are still working on it. However, platform limitations are severe, only so much improvement is possible here. If you have reproducible crashes please report them.

**Comment by TPS** [comment]
@palant I'm very sorry for the thread hijacking, but I've been unable to raise anyone any official way, & the internal crash-reporting has never worked to contact that way either.  I'm finding it hard to believe, though, almost nothing can be done, given the number of apps that seem not to have the problem.…  Is the only practical to rework this as VPN?  How do I take this discussion someplace more appropriate & be ignored? 

@edent @All I apologize for the thread spam & my desperation.  I will move off this channel ASAP.

**Comment by Nick-White** [comment]
@TPS @palant VPN is MUCH WORSE performance wise and you have to manually implement TCP. You can look at AdGuard that supports both (proxy and VPN) and VPN is much slower and more error prone. I think the current approach is fine, but needs some essential missing features (custom filters, logging), memory improvements.

@All Sorry for responding here.

**Comment by rjeschke** [comment]
@edent sure, you're definitely right, will merge this one today.

**Comment by rjeschke** [comment]
Merged as [69906e798846](https://hg.adblockplus.org/adblockplusandroid/rev/69906e798846).

**Pull request closed without merging**
